Repository alma/alma-installments-prestashop, pull requests merged in 2024-12, with the labels that each got.

#612 feat: Send the endpoint_url during the upgrade
  alma/controllers/front/cmsdataexport.php
  alma/lib/Helpers/CmsDataHelper.php
  alma/tests/Unit/Helper/CmsDataHelperTest.php
  alma/upgrade/upgrade-4.6.0.php
Labels: skip-changelog, type: feature

#614 fix: Custom Description for payment button credit
  alma/lib/Helpers/PaymentOptionHelper.php
Labels: type: feature

#616 Fix data theme for gathercmsdata
  alma/lib/Builders/Validators/index.php
  alma/lib/Helpers/CmsDataHelper.php
  alma/lib/Helpers/ThemeHelper.php
  alma/lib/Proxy/index.php
  alma/tests/Unit/Helper/CmsDataHelperTest.php
  alma/tests/Unit/Proxy/index.php
  alma/tests/Unit/Validators/index.php
Labels: type: feature

#617 Fix theme helper
  alma/lib/Helpers/ThemeHelper.php
Labels: skip-changelog, type: bugfix

#621 fix: inject Module in OrderHelper to use translation function
  alma/controllers/hook/DisplayRefundsHookController.php
  alma/controllers/hook/StateHookController.php
  alma/lib/Helpers/OrderHelper.php
  alma/lib/Helpers/ShareOfCheckoutHelper.php
Labels: type: bugfix
