Repository alma/alma-installments-prestashop, pull requests merged in 2024-11, with the labels that each got.

#594 feat: Update wording for In-Page advanced feature
  alma/lib/Forms/InpageAdminFormBuilder.php
  alma/translations/en.php
  alma/translations/fr.php
Labels: type: feature

#593 fix: issue with some translation in payment buttons
  alma/lib/Helpers/PaymentOptionTemplateHelper.php
  alma/lib/Helpers/PlanHelper.php
  alma/lib/Helpers/TranslationHelper.php
  alma/tests/Unit/Helper/PaymentOptionTemplateHelperTest.php
  alma/tests/Unit/Helper/TranslationHelperTest.php
  alma/translations/en.php
  alma/translations/fr.php
Labels: type: bugfix

#598 Prevent crash when there is not quantity input on product page
  alma/views/js/alma-product-insurance.js
Labels: bug, Insurance, type: bugfix
