Repository alma/alma-installments-prestashop, pull requests merged in 2024-10, with the labels that each got.

#575 Integrate credit for in page
  alma/controllers/front/payment.php
  alma/controllers/hook/DisplayPaymentHookController.php
  alma/lib/Helpers/ConfigurationHelper.php
  alma/lib/Helpers/PaymentOptionHelper.php
  alma/lib/Helpers/PaymentOptionTemplateHelper.php
  alma/lib/Model/PaymentData.php
  alma/lib/Services/PaymentService.php
  alma/tests/Unit/Helper/ConfigurationHelperTest.php
Labels: feature

#576 fix: setContainer Ps Account install module
  alma/alma.php
Labels: type: bugfix

#573 fix: paymentValidation in validation controller since HMAC
  alma/controllers/front/ipn.php
  alma/controllers/front/validation.php
  alma/lib/Validators/PaymentValidation.php
  alma/tests/Unit/Validators/PaymentValidationTest.php
Labels: type: bugfix

#572 fix: automatic height insurance widget
  alma/lib/Helpers/HookHelper.php
  alma/views/css/alma-insurance.css
  alma/views/js/alma-product-insurance.js
  alma/views/templates/hook/displayProductActions.tpl
Labels: type: bugfix

#577 fix: display widget on PS 1.7.0.6
  alma/views/css/alma-insurance.css
Labels: type: bugfix

#582 Reuse Aqua workflow from alma/actions
  .github/workflows/aqua.yml
Labels: type: security

#583 Reintroduce full Aqua workflow due to repository privacy issues
  .github/workflows/aqua.yml
Labels: type: security

#591 Improve insurance integration stability & prevent unnecessary reloading of widget
  alma/controllers/hook/DisplayProductActionsHookController.php
  alma/views/js/alma-product-insurance.js
Labels: Insurance, type: bugfix, type: refactor

#589 fix: Impossible configure Alma if PS Account version is lower 5.0
  alma/alma.php
  alma/controllers/hook/GetContentHookController.php
  alma/exceptions/CompatibilityPsAccountsException.php
  alma/translations/de.php
  alma/translations/en.php
  alma/translations/es.php
  alma/translations/fr.php
  alma/translations/it.php
  alma/translations/nl.php
  alma/translations/pt.php
  alma/views/templates/hook/getContent.tpl
  alma/views/templates/hook/notificationConfiguration.tpl
Labels: type: hotfix
