Repository alma/alma-installments-prestashop, pull requests merged in 2024-07, with the labels that each got.

#497 [DEVX] Fix branch for release-drafter + don't publish internal changes in changelog
  .github/pr-labeler.yml
  .github/release-drafter.yml
  .github/workflows/backport-pull-request.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/release-publish.yml
  .github/workflows/release-pull-request.yml
Labels: type: devx

#498 [DEVX] Merge release-drafter update on main
  .github/pr-labeler.yml
  .github/release-drafter.yml
  .github/workflows/backport-pull-request.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/release-publish.yml
  .github/workflows/release-pull-request.yml
Labels: type: devx

#499 fix: add insurance from cart page with multiple execution
  alma/views/js/alma-cart-insurance.js
Labels: feature

#500 [DEVX] Update Slack release message
  .github/renovate.json
  .github/workflows/release-publish.yml
Labels: type: devx

#509 fix: Issue insurance for product not eligible created after import
  alma/views/js/alma-cart-insurance.js
  alma/views/js/alma-product-insurance.js
Labels: type: bugfix

#508 fix: Issue quantity insurance if we change quantity in cart
  alma/views/js/alma-cart-insurance.js
Labels: type: bugfix

#506 fix: Issue PS Account with PS 8.1.7
  alma/config/admin/services.yml
Labels: type: bugfix

#510 fix: Avoid change quantity with module pscartdropdown for insurance
  alma/controllers/hook/FrontHeaderHookController.php
  alma/views/js/alma-insurance.js
Labels: type: bugfix

#503 [DEVX] Add info for Marketplace publication in task release
  Taskfile.yml
Labels: type: devx

#514 fix: Declaration LinkFactory
  alma/lib/Factories/LinkFactory.php
  alma/lib/Services/InsuranceProductService.php
  alma/tests/Unit/Services/InsuranceProductServiceTest.php
Labels: type: bugfix

#515 fix: Issue with insurance on mobile display
  alma/views/js/alma-insurance.js
  alma/views/js/alma-product-insurance.js
Labels: type: feature

#523 [DEVX] Fix release PR not triggering workflows
  .github/workflows/release-pull-request.yml
Labels: type: devx

#519 [compatibility] feat: Add column in orders list with Has insurance
  alma/alma.php
  alma/controllers/hook/ActionAdminOrdersListingFieldsModifierHookController.php
  alma/lib/Helpers/HookHelper.php
Labels: type: feature

#520 [compatibility] feat: Remove insurance product when removing the product with insurance
  alma/alma.php
  alma/lib/Helpers/HookHelper.php
Labels: type: feature

#525 [compatibility] feat: Send a sessionId to the Insurance API
  alma/controllers/hook/DisplayCartExtraProductActionsHookController.php
  alma/controllers/hook/DisplayProductActionsHookController.php
  alma/lib/Services/InsuranceApiService.php
Labels: type: feature

#526 [compatibility] feat: Avoid to change the quantity in the item on the cart if the ins…
  alma/views/css/alma-insurance.css
Labels: type: feature

#527 [compatibility] feat: Add notification in the order page if the order has an insurance
  alma/lib/Helpers/HookHelper.php
Labels: type: feature

#528 [compatibility] feat: Create the subscription when the order payment is validated
  alma/lib/Model/InsuranceProduct.php
Labels: type: feature

#531 fix: compatibility PS 1.6 during installing module
  alma/alma.php
Labels: type: bugfix

#532 fix: Issue price widget in Cart Item
  alma/controllers/hook/DisplayCartExtraProductActionsHookController.php
  alma/lib/smarty.php
  alma/views/templates/hook/_partials/cartProducts.tpl
  alma/views/templates/hook/_partials/widgetAddInsuranceProducts.tpl
  alma/views/templates/hook/displayCartExtraProductActions.tpl
Labels: type: bugfix

#533 Fix: add quantity insurance in the product and display cart item
  alma/views/js/alma-product-insurance.js
  alma/views/templates/hook/_partials/itemCartInsuranceProduct.tpl
Labels: type: bugfix

#536 fix: remove dump
  alma/views/templates/hook/displayCartExtraProductActions.tpl
Labels: skip-changelog

#535 Fix renovate configuration and disable major composer updates
  .github/renovate.json
Labels: type: devx

#541 fix: install module without ConfigCache about PS Account
  alma/alma.php
Labels: type: bugfix

#542 fix: change order status error
  alma/lib/Services/OrderService.php
Labels: type: bugfix

#543 fix: openmodal insurance in the first load product page
  alma/views/js/alma-product-insurance.js
Labels: type: bugfix
