Repository alma/alma-installments-prestashop, pull requests merged in 2024-09, with the labels that each got.

#566 fix: Inpage on prestashop 1.6 with third party module of checkout
  alma/views/js/alma-inpage.js
Labels: type: bugfix

#565 fix: install module if container of getService Ps_account is null
  alma/alma.php
  alma/controllers/hook/FrontHeaderHookController.php
  alma/exceptions/CompatibilityPsAccountException.php
  alma/tests/Unit/Controllers/Front/index.php
Labels: type: bugfix

#568 Feature/ecom 2062 ps fix insurance for retrofutur
  alma/controllers/hook/ActionFrontControllerSetVariablesHookController.php
  alma/controllers/hook/DisplayProductActionsHookController.php
  alma/views/js/alma-product-insurance.js
  alma/views/templates/hook/displayProductActions.tpl
Labels: type: feature

#571 chore(naming): rename function to be clearer
  alma/lib/Helpers/PaymentOptionHelper.php
  alma/lib/Helpers/PlanHelper.php
  alma/lib/Services/PaymentService.php
  alma/tests/Unit/Helper/PlanHelperTest.php
Labels: type: chore
