Repository alma/alma-installments-prestashop, pull requests merged in 2024-08, with the labels that each got.

#547 fix: install module with ps_account from ps17 to ps8
  alma/config/admin/services.yml
Labels: type: bugfix

#548 fix: display multiple notification dashboard on ps17
  alma/views/templates/hook/notificationConfiguration.tpl
Labels: type: bugfix

#546 [ALF-135] Add a semgrep rule to ensure compatibility with Prestashop v1.6
  .github/workflows/ci.yaml
  semgrep/rules/prestashop-compatibility-no-use-keyword.yaml
Labels: type: devx

#550 fix: eligible limit of feePlans
  alma/lib/Helpers/FeePlanHelper.php
  alma/tests/Unit/Helper/FeePlanHelperTest.php
Labels: type: bugfix

#551 fix: create payment with object category in product
  alma/controllers/front/payment.php
  alma/lib/Helpers/ProductHelper.php
  alma/lib/Model/CartData.php
  alma/tests/Unit/Helper/ProductHelperTest.php
  alma/tests/Unit/Model/CartDataTest.php
Labels: type: bugfix

#552 fix: unit-test
  alma/tests/Unit/Model/CartDataTest.php
Labels: skip-changelog, type: bugfix

#554 fix: compatibility 1.7.0
  alma/views/js/alma-product-insurance.js
  alma/views/templates/hook/notificationConfiguration.tpl
Labels: skip-changelog, type: bugfix

#545 feat: Shipment info analysis
  alma/alma.php
  alma/composer.json
  alma/controllers/hook/ActionObjectUpdateAfter.php
  alma/exceptions/AlmaActionObjectUpdateException.php
  alma/lib/Factories/OrderFactory.php
  alma/lib/Helpers/HookHelper.php
  alma/tests/Unit/Controllers/Hook/ActionObjectUpdateAfterTest.php
Labels: type: feature

#544 [DEVX] Check latest release if no release draft to be published
  .github/workflows/hotfix-pull-request.yml
  .github/workflows/release-publish.yml
  .github/workflows/release-pull-request.yml
Labels: type: devx

#562 Chore/add html coverage report
  Taskfile.yml
  alma/phpunit.ci.xml
  alma/tests/ReportConfigForHTMLReport.php
  alma/tests/Unit/Builders/Repositories/InsuranceProductRepositoryBuilderTest.php
  alma/tests/bootstrap.php
Labels: type: chore
