Repository alma/alma-installments-prestashop, pull requests merged in 2025-02, with the labels that each got.

#631 feat: Merchant conversion data
  alma/alma.php
  alma/composer.json
  alma/controllers/hook/ActionCartSaveHookController.php
  alma/controllers/hook/ActionValidateOrderHookController.php
  alma/controllers/hook/PaymentOptionsHookController.php
  alma/lib/Builders/Helpers/EligibilityHelperBuilder.php
  alma/lib/Helpers/ConfigurationHelper.php
  alma/lib/Helpers/EligibilityHelper.php
  alma/lib/Helpers/FeePlanHelper.php
  alma/lib/Helpers/PaymentHelper.php
  alma/lib/Helpers/SettingsHelper.php
  alma/lib/Model/AlmaBusinessDataModel.php
  alma/lib/Model/ClientModel.php
  alma/lib/Model/InsuranceProduct.php
  alma/lib/Model/PaymentData.php
  alma/lib/Repositories/AlmaBusinessDataRepository.php
  alma/lib/Services/AlmaBusinessDataService.php
  alma/lib/Services/PaymentService.php
  alma/lib/Traits/BuilderTrait.php
  alma/lib/Traits/ObjectModelTrait.php
  alma/lib/Validators/PaymentValidation.php
  alma/tests/Unit/Helper/EligibilityHelperTest.php
  alma/tests/Unit/Helper/FeePlanHelperTest.php
  alma/tests/Unit/Helper/ProductHelperTest.php
  alma/tests/Unit/Services/AlmaBusinessDataServiceTest.php
  alma/upgrade/upgrade-4.7.0.php
Labels: type: feature

#639 fix: Rollback file removed for PS 1.6
  alma/views/templates/hook/_partials/displayPayment_pnx.tpl
Labels: skip-changelog, type: bugfix

#640 fix: create AlmaObjectModel for compatibility with PS1.6 + remove unique key alma_payment_id
  alma/lib/Model/AlmaBusinessDataModel.php
  alma/lib/Model/AlmaObjectModel.php
  alma/lib/Model/InsuranceProduct.php
  alma/tests/Unit/Services/AlmaBusinessDataServiceTest.php
Labels: skip-changelog, type: bugfix

#646 fix: Deduplicate business event calls
  alma/alma.php
  alma/controllers/hook/ActionCartSaveHookController.php
  alma/controllers/hook/ActionValidateOrderHookController.php
  alma/lib/Repositories/AlmaBusinessDataRepository.php
  alma/lib/Services/AlmaBusinessDataService.php
  alma/tests/Unit/Services/AlmaBusinessDataServiceTest.php
  alma/upgrade/upgrade-4.7.1.php
Labels: type: bugfix

#643 fix: controller unknown for marketplace tool
  alma/lib/Hooks/HookController.php
Labels: type: bugfix

#647 Fix/pre commit
  .gitignore
  .pre-commit-config.yaml
  Taskfile.yml
  dockerfile.md
  lint.Dockerfile
  scripts/lint-fix.sh
  scripts/lint.sh
  scripts/php-compatibility.sh
Labels: type: bugfix

#653 Fix force type to string for cms datatheme version
  alma/lib/Helpers/ThemeHelper.php
Labels: type: feature

#652 Use new payment endpoint for order status
  alma/controllers/hook/StateHookController.php
  alma/exceptions/OrderServiceException.php
  alma/lib/Helpers/ClientHelper.php
  alma/lib/Services/OrderService.php
  alma/lib/Validators/PaymentValidation.php
  alma/tests/Unit/Helper/ClientHelperTest.php
  alma/tests/Unit/Services/OrderServiceTest.php
Labels: type: feature

#654 Add error code 403 for invalid signature in gather cms data
  alma/controllers/front/cmsdataexport.php
  alma/tests/Unit/Controllers/Front/CmsDataExportTest.php
Labels: type: feature

#655 Fix/maj linter
  .github/workflows/ci.yaml
  Taskfile.yml
  alma/.php-cs-fixer.dist.php
  dockerfile.md
  lint.Dockerfile
  php-compatibility.Dockerfile
  scripts/lint-ci.sh
  scripts/lint-fix.sh
  scripts/lint.sh
  scripts/php-compatibility.sh
Labels: type: bugfix

#660 fix: Issue checkout process with old Prestashop version
  alma/controllers/hook/ActionCartSaveHookController.php
Labels: type: bugfix
