Repository alma/alma-installments-prestashop, pull requests merged in 2025-03, with the labels that each got.

#662 feat: Weird calls to /return-urls. Payment id is undefined or absent
  alma/views/js/alma-inpage.js
Labels: type: feature

#665 fix: handle In-page if payment option is checked before page loaded
  alma/views/js/alma-inpage.js
Labels: type: bugfix

#664 feat: update README for compatibility version
  README.md
Labels: skip-changelog

#676 Fix and update Renovate configuration
  .github/renovate.json
  .github/renovate.json5
Labels: type: chore
