Repository alma/alma-installments-prestashop, pull requests merged in 2025-01, with the labels that each got.

#625 fix: unit test for context link issue from ps_checkout module
  alma/lib/Helpers/ContextHelper.php
  alma/tests/Unit/Helper/ContextHelperTest.php
Labels: type: bugfix

#626 fix: migration after refacto
  alma/alma.php
Labels: type: bugfix

#632 fix: Avoid error about get customer for eligibility of cart widget
  alma/lib/Model/PaymentData.php
Labels: type: bugfix

#633 feat: Add position at checkout for GatherCMSData
  alma/lib/Helpers/CmsDataHelper.php
  alma/lib/Model/AlmaModuleModel.php
  alma/tests/Unit/Helper/CmsDataHelperTest.php
  alma/tests/Unit/Model/AlmaModuleModelTest.php
Labels: type: feature

#636 fix: Update HTML element in FrontHeaderHookController for better semantic
  alma/controllers/hook/FrontHeaderHookController.php
Labels: type: bugfix

#637 Remove ping to France in Slack release messages
  .github/workflows/release-publish.yml
Labels: type: devx
